# Generated by Django 6.0 on 2026-02-20 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myhotel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HotelProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("hotel_name", models.CharField(max_length=255)),
                ("contact_location", models.CharField(max_length=255)),
                ("hotel_id", models.CharField(max_length=100, unique=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hotel_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
