# Generated by Django 6.0 on 2026-02-20

from decimal import Decimal
from django.db import migrations


def seed_products_services(apps, schema_editor):
    Product = apps.get_model("myhotel", "Product")
    Service = apps.get_model("myhotel", "Service")

    products = [
        ("Bottled Water (1L)", Decimal("1500.00")),
        ("Soft Drink", Decimal("2500.00")),
        ("Breakfast Buffet", Decimal("18000.00")),
        ("Lunch Meal", Decimal("22000.00")),
        ("Dinner Meal", Decimal("28000.00")),
        ("Laundry Detergent Pack", Decimal("5000.00")),
        ("Toiletries Kit", Decimal("7000.00")),
        ("Extra Bed Sheet Set", Decimal("12000.00")),
    ]

    services = [
        ("Room Cleaning", Decimal("10000.00")),
        ("Laundry Service", Decimal("15000.00")),
        ("Airport Pickup", Decimal("45000.00")),
        ("Airport Drop-off", Decimal("45000.00")),
        ("Spa Session", Decimal("60000.00")),
        ("Conference Room (Per Hour)", Decimal("35000.00")),
        ("City Tour Arrangement", Decimal("80000.00")),
        ("Late Checkout", Decimal("20000.00")),
    ]

    for name, price in products:
        Product.objects.update_or_create(name=name, defaults={"price": price})

    for name, price in services:
        Service.objects.update_or_create(name=name, defaults={"price": price})


def unseed_products_services(apps, schema_editor):
    Product = apps.get_model("myhotel", "Product")
    Service = apps.get_model("myhotel", "Service")

    product_names = [
        "Bottled Water (1L)",
        "Soft Drink",
        "Breakfast Buffet",
        "Lunch Meal",
        "Dinner Meal",
        "Laundry Detergent Pack",
        "Toiletries Kit",
        "Extra Bed Sheet Set",
    ]

    service_names = [
        "Room Cleaning",
        "Laundry Service",
        "Airport Pickup",
        "Airport Drop-off",
        "Spa Session",
        "Conference Room (Per Hour)",
        "City Tour Arrangement",
        "Late Checkout",
    ]

    Product.objects.filter(name__in=product_names).delete()
    Service.objects.filter(name__in=service_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("myhotel", "0002_hotelprofile"),
    ]

    operations = [
        migrations.RunPython(seed_products_services, unseed_products_services),
    ]
