# Generated by Django 6.0 on 2026-02-20

from decimal import Decimal
from django.db import migrations


def update_catalog_to_wholesale(apps, schema_editor):
    Product = apps.get_model("myhotel", "Product")
    Service = apps.get_model("myhotel", "Service")

    old_product_names = [
        "Bottled Water (1L)",
        "Soft Drink",
        "Breakfast Buffet",
        "Lunch Meal",
        "Dinner Meal",
        "Laundry Detergent Pack",
        "Toiletries Kit",
        "Extra Bed Sheet Set",
    ]

    old_service_names = [
        "Room Cleaning",
        "Laundry Service",
        "Airport Pickup",
        "Airport Drop-off",
        "Spa Session",
        "Conference Room (Per Hour)",
        "City Tour Arrangement",
        "Late Checkout",
    ]

    Product.objects.filter(name__in=old_product_names).delete()
    Service.objects.filter(name__in=old_service_names).delete()

    wholesale_products = [
        ("Rice 25kg Bag", Decimal("78000.00")),
        ("Sugar 25kg Bag", Decimal("92000.00")),
        ("Wheat Flour 25kg Bag", Decimal("70000.00")),
        ("Cooking Oil 20L", Decimal("165000.00")),
        ("Maize Flour 25kg Bag", Decimal("58000.00")),
        ("Bottled Water Carton (24 pcs)", Decimal("12500.00")),
        ("Soft Drink Crate (24 bottles)", Decimal("23000.00")),
        ("Toilet Paper Bale (40 rolls)", Decimal("52000.00")),
    ]

    wholesale_services = [
        ("Bulk Delivery - Within City", Decimal("35000.00")),
        ("Bulk Delivery - Upcountry", Decimal("120000.00")),
        ("Warehouse Storage (Per Day)", Decimal("45000.00")),
        ("Loading and Offloading", Decimal("30000.00")),
        ("Inventory Packaging Service", Decimal("55000.00")),
        ("Private Label Repackaging", Decimal("90000.00")),
        ("Procurement Assistance", Decimal("75000.00")),
        ("Priority Dispatch", Decimal("65000.00")),
    ]

    for name, price in wholesale_products:
        Product.objects.update_or_create(name=name, defaults={"price": price})

    for name, price in wholesale_services:
        Service.objects.update_or_create(name=name, defaults={"price": price})


def revert_catalog_to_retail(apps, schema_editor):
    Product = apps.get_model("myhotel", "Product")
    Service = apps.get_model("myhotel", "Service")

    wholesale_product_names = [
        "Rice 25kg Bag",
        "Sugar 25kg Bag",
        "Wheat Flour 25kg Bag",
        "Cooking Oil 20L",
        "Maize Flour 25kg Bag",
        "Bottled Water Carton (24 pcs)",
        "Soft Drink Crate (24 bottles)",
        "Toilet Paper Bale (40 rolls)",
    ]

    wholesale_service_names = [
        "Bulk Delivery - Within City",
        "Bulk Delivery - Upcountry",
        "Warehouse Storage (Per Day)",
        "Loading and Offloading",
        "Inventory Packaging Service",
        "Private Label Repackaging",
        "Procurement Assistance",
        "Priority Dispatch",
    ]

    Product.objects.filter(name__in=wholesale_product_names).delete()
    Service.objects.filter(name__in=wholesale_service_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("myhotel", "0003_seed_products_services"),
    ]

    operations = [
        migrations.RunPython(update_catalog_to_wholesale, revert_catalog_to_retail),
    ]
