# Generated by Django 6.0 on 2026-02-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myhotel", "0004_update_catalog_to_wholesale"),
    ]

    operations = [
        migrations.AddField(
            model_name="myorder",
            name="admin_feedback",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="myorder",
            name="estimated_completion_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="service",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="myorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Accepted", "Accepted"),
                    ("Rejected", "Rejected"),
                    ("Completed", "Completed"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
