# Generated by Django 6.0 on 2026-02-20

from decimal import Decimal
from django.db import migrations, models


def backfill_unit_price(apps, schema_editor):
    OrderItem = apps.get_model("myhotel", "OrderItem")
    for item in OrderItem.objects.select_related("product", "service").all():
        if item.product_id and item.product:
            item.unit_price = item.product.price
        elif item.service_id and item.service:
            item.unit_price = item.service.price
        else:
            item.unit_price = Decimal("0.00")
        item.save(update_fields=["unit_price"])


class Migration(migrations.Migration):

    dependencies = [
        ("myhotel", "0005_order_feedback_and_catalog_activation"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="service",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.RunPython(backfill_unit_price, migrations.RunPython.noop),
    ]
