# Generated by Django 6.0 on 2026-02-20

from django.db import migrations


def seed_quantities(apps, schema_editor):
    Product = apps.get_model("myhotel", "Product")
    Service = apps.get_model("myhotel", "Service")

    product_quantities = {
        "Rice 25kg Bag": 120,
        "Sugar 25kg Bag": 90,
        "Wheat Flour 25kg Bag": 110,
        "Cooking Oil 20L": 70,
        "Maize Flour 25kg Bag": 140,
        "Bottled Water Carton (24 pcs)": 260,
        "Soft Drink Crate (24 bottles)": 180,
        "Toilet Paper Bale (40 rolls)": 100,
    }

    service_capacities = {
        "Bulk Delivery - Within City": 40,
        "Bulk Delivery - Upcountry": 20,
        "Warehouse Storage (Per Day)": 50,
        "Loading and Offloading": 65,
        "Inventory Packaging Service": 45,
        "Private Label Repackaging": 30,
        "Procurement Assistance": 35,
        "Priority Dispatch": 25,
    }

    for name, qty in product_quantities.items():
        Product.objects.filter(name=name).update(quantity=qty)

    for name, qty in service_capacities.items():
        Service.objects.filter(name=name).update(quantity=qty)


class Migration(migrations.Migration):

    dependencies = [
        ("myhotel", "0006_item_quantity_and_unit_price"),
    ]

    operations = [
        migrations.RunPython(seed_quantities, migrations.RunPython.noop),
    ]
